server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    config:
      enabled: false

    gateway:
      routes:
        - id: client-microservice
          uri: lb://client-microservice
          predicates:
            - Path=/api/v1/clientes/**
        - id: account-microservice
          uri: lb://account-microservice
          predicates:
            - Path=/api/v1/cuentas/**
        - id: account-movements
          uri: lb://account-microservice
          predicates:
            - Path=/api/v1/movimientos/**
        - id: account-reports
          uri: lb://account-microservice
          predicates:
            - Path=/api/v1/reportes/**

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  level:
    root: info
    org.springframework.cloud.gateway: trace
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: info
